server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

jwt:
  secret: secret_key
  lifetime: 30m

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project_management_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

